In [42]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [43]:
# import gdown

# file_id = "1wwt7Pu3PhRel40a3OAlj0Yfkw1HKGtq8"
# url = f"https://drive.google.com/uc?id={file_id}"

# gdown.download(url, "../models/data.csv", quiet=False)

In [44]:
data = pd.read_csv("../data/cleaned_data.csv")
data.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  3.0     145.0  233.0  1.0      0.0    150.0      0      2.3   
1  37.0  1.0  2.0     130.0  250.0  0.0      1.0    187.0      0      3.5   
2  41.0  0.0  1.0     130.0  204.0  0.0      0.0    172.0      0      1.4   
3  56.0  1.0  1.0     120.0  236.0  0.0      1.0    178.0      0      0.8   
4  54.4  0.0  0.0     120.0  354.0  0.0      1.0    163.0      1      0.6   

   slope   ca  thal  target  
0      0  0.0   1.0       1  
1      0  0.0   2.0       1  
2      2  0.0   2.0       1  
3      2  0.0   2.0       1  
4      2  0.0   2.0       1

In [45]:
x = data.drop('target', axis=1)
y = data['target']

In [46]:
x.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  3.0     145.0  233.0  1.0      0.0    150.0      0      2.3   
1  37.0  1.0  2.0     130.0  250.0  0.0      1.0    187.0      0      3.5   
2  41.0  0.0  1.0     130.0  204.0  0.0      0.0    172.0      0      1.4   
3  56.0  1.0  1.0     120.0  236.0  0.0      1.0    178.0      0      0.8   
4  54.4  0.0  0.0     120.0  354.0  0.0      1.0    163.0      1      0.6   

   slope   ca  thal  
0      0  0.0   1.0  
1      0  0.0   2.0  
2      2  0.0   2.0  
3      2  0.0   2.0  
4      2  0.0   2.0

In [47]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.15, random_state=1)

In [49]:
print(f'train set: {len(xTrain)}')
print(f'train set: {len(xTest)}')

train set: 256
train set: 46


In [50]:
from sklearn.preprocessing import StandardScaler

needingScalingColumns = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
scaler = StandardScaler()
xTrain[needingScalingColumns] = scaler.fit_transform(xTrain[needingScalingColumns])
xTest[needingScalingColumns] = scaler.transform(xTest[needingScalingColumns])


In [51]:
import joblib

joblib.dump(scaler, '../models/scaler.pkl')

['../models/scaler.pkl']

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


lrModel = LogisticRegression()
lrModel.fit(xTrain, yTrain)
yPredLr =lrModel.predict(xTest)


print("🔍 Logistic Regression")
print("Accuracy:", accuracy_score(yTest, yPredLr))
print("Confusion Matrix:\n", confusion_matrix(yTest, yPredLr))
print("Classification Report:\n", classification_report(yTest, yPredLr))

🔍 Logistic Regression
Accuracy: 0.782608695652174
Confusion Matrix:
 [[15  7]
 [ 3 21]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.68      0.75        22
           1       0.75      0.88      0.81        24

    accuracy                           0.78        46
   macro avg       0.79      0.78      0.78        46
weighted avg       0.79      0.78      0.78        46



In [53]:
from sklearn.svm import SVC

svmModel = SVC()
svmModel.fit(xTrain, yTrain)
yPredSvm = svmModel.predict(xTest)

print("🔍 Support Vector Machine")
print("Accuracy:", accuracy_score(yTest, yPredSvm))
print("Confusion Matrix:\n", confusion_matrix(yTest, yPredSvm))
print("Classification Report:\n", classification_report(yTest, yPredSvm))

🔍 Support Vector Machine
Accuracy: 0.8260869565217391
Confusion Matrix:
 [[15  7]
 [ 1 23]]
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.68      0.79        22
           1       0.77      0.96      0.85        24

    accuracy                           0.83        46
   macro avg       0.85      0.82      0.82        46
weighted avg       0.85      0.83      0.82        46



In [54]:
from sklearn.tree import DecisionTreeClassifier

treeModel = DecisionTreeClassifier(criterion='entropy')  # ID3 uses entropy
treeModel.fit(xTrain, yTrain)
yPredTree = treeModel.predict(xTest)

print("🔍 Decision Tree (ID3)")
print("Accuracy:", accuracy_score(yTest, yPredTree))
print("Confusion Matrix:\n", confusion_matrix(yTest, yPredTree))
print("Classification Report:\n", classification_report(yTest, yPredTree))


🔍 Decision Tree (ID3)
Accuracy: 0.717391304347826
Confusion Matrix:
 [[16  6]
 [ 7 17]]
Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.73      0.71        22
           1       0.74      0.71      0.72        24

    accuracy                           0.72        46
   macro avg       0.72      0.72      0.72        46
weighted avg       0.72      0.72      0.72        46



In [55]:
from sklearn.neighbors import KNeighborsClassifier

knnModel = KNeighborsClassifier(n_neighbors=5)
knnModel.fit(xTrain, yTrain)
yPredKnn = knnModel.predict(xTest)

print("🔍 K-Nearest Neighbors (KNN)")
print("Accuracy:", accuracy_score(yTest, yPredKnn))
print("Confusion Matrix:\n", confusion_matrix(yTest, yPredKnn))
print("Classification Report:\n", classification_report(yTest, yPredKnn))


🔍 K-Nearest Neighbors (KNN)
Accuracy: 0.8043478260869565
Confusion Matrix:
 [[15  7]
 [ 2 22]]
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.68      0.77        22
           1       0.76      0.92      0.83        24

    accuracy                           0.80        46
   macro avg       0.82      0.80      0.80        46
weighted avg       0.82      0.80      0.80        46



In [83]:

joblib.dump(svmModel, '../models/heart_svmModel.pkl')
joblib.dump(lrModel, '../models/heart_lrModel.pkl')
joblib.dump(knnModel, '../models/heart_knnModel.pkl')
joblib.dump(treeModel, '../models/heart_treeModel.pkl')

['../models/heart_treeModel.pkl']

In [76]:
sample_inputs = [
    # 🔴 Likely Heart Disease
    [64, 1, 3, 150, 270, 0, 0, 135, 1, 2.9, 1, 2, 2],
    [58, 0, 2, 130, 300, 0, 1, 128, 1, 2.5, 2, 1, 3],
    [60, 1, 1, 140, 285, 1, 1, 120, 1, 3.0, 2, 2, 2],
    [55, 1, 2, 150, 245, 0, 1, 132, 1, 2.8, 1, 1, 2],
    [66, 1, 0, 160, 290, 1, 0, 110, 1, 2.6, 2, 3, 3],

    # 🟢 Likely No Heart Disease
    [44, 0, 1, 120, 210, 0, 1, 165, 0, 0.2, 1, 0, 2],
    [36, 1, 0, 118, 190, 0, 0, 172, 0, 0.0, 1, 0, 2],
    [47, 0, 1, 130, 225, 0, 0, 162, 0, 0.1, 2, 0, 2],
    [39, 1, 0, 115, 198, 0, 0, 168, 0, 0.0, 1, 0, 2],
    [43, 0, 1, 128, 215, 0, 0, 175, 0, 0.1, 1, 0, 2]
]


In [79]:
prediction1 = lrModel.predict(sample_inputs)
print(prediction1)
# print("Prediction:", "Heart Disease" if prediction == 1 else "No Heart Disease")

[0 0 0 0 0 0 0 0 0 0]


c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [ ]:
prediction2 = svmModel.predict(sample_inputs) # type: ignore
print(prediction2)
# print("Prediction:", "Heart Disease" if prediction == 1 else "No Heart Disease")

[0 0 0 0 0 0 0 0 0 0]


c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [81]:
prediction3 = treeModel.predict(sample_inputs)
print(prediction3)
# print("Prediction:", "Heart Disease" if prediction == 1 else "No Heart Disease")

[1 0 1 1 0 1 0 1 0 1]


c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [ ]:
prediction4 = knnModel.predict(sample_inputs) # type: ignore
print(prediction4)
# print("Prediction:", "Heart Disease" if prediction == 1 else "No Heart Disease")

[1 1 1 1 1 1 1 1 1 1]


c:\Users\acer\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
